site_name: Godot LuaAPI
repo_url: https://github.com/WeaselGames/godot_luaAPI
plugins:
  - search
extra:
  version:
    provider: mike
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - toc:
      toc_depth: 3
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details

nav:
  - index.md
  - Getting Started:
      - getting_started/before_you_start.md
      - getting_started/installation.md
  - Classes:
      - classes/lua_api.md
      - classes/lua_coroutine.md
      - classes/lua_error.md
      - classes/lua_callable_extra.md
      - classes/lua_tuple.md
  - Examples:
      - examples/objects.md
      - examples/lua_callable.md

theme:
  name: material
  logo: assets/sandcastle_icon.png
  favicon: assets/sandcastle_icon.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.top
    - navigation.footer
    - search.highlight
    - content.code.copy
    - content.code.annotate
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: indigo
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: indigo
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
